// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wvrreqwvgrsvmrwuavna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2cnJlcXd2Z3Jzdm1yd3Vhdm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzNzg2NTcsImV4cCI6MjA5NTk1NDY1N30.yFiDakXWBp4bzOKtjDHK2GuV9VeuWD4nTQ1H7NGLvyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);