// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://iquvxkczxzftocvtbtvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxdXZ4a2N6eHpmdG9jdnRidHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NTcyODAsImV4cCI6MjA5MjUzMzI4MH0.QAfst7Z9zbe5yA3XIUkNopr2lnmJTSeKR964FCs2WgE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);